apiVersion: v1
kind: Pod
metadata:
  name: ci
  labels:
    app:
      ci
spec:
  containers:
    - name: ci
      image: raphaelhoffa/ci:latest

---

apiVersion: v1
kind: Service
metadata:
  name: ci-service
spec:
  selector:
    app: ci
  ports:
    - port: 8080
