# apiVersion: v1  
# kind: ConfigMap  
# metadata:  
#   name: {{.Values.name}}  
# data:  
# {{.Values.env.config | toYaml | indent 2}}  
# ---  
# {{- end}}  
  
# {{- if .Values.env.secrets}}  
# apiVersion: v1  
# kind: Secret  
# metadata:  
#   name: {{.Values.name}}  
# stringData:  
# {{.Values.env.secrets | toYaml | indent 2}}  
# ---  
# {{- end}}  
  
# {{- if .Values.dockercfg}}  
# apiVersion: v1  
# kind: Secret  
# metadata:  
#   name: {{.Values.name}}-dockercfg  
#   annotations:  
#     harness.io/skip-versioning: true  
# data:  
#   .dockercfg: {{.Values.dockercfg}}  
# type: kubernetes.io/dockercfg  
# ---  
# {{- end}}  
  
apiVersion: apps/v1  
kind: Deployment  
metadata:  
  name: cd-deployment  
spec:  
  replicas: 3  
  selector:  
    matchLabels:  
      app: cd  
  template:  
    metadata:  
      labels:  
        app: cd  
    spec:  
      imagePullSecrets:  
      - name: cd
      containers:  
      - name: cd  
        image: raphaelhoffa/ci  
        # envFrom:  
        # {{- if .Values.env.config}}  
        # - configMapRef:  
        #     name: {{.Values.name}}  
        # {{- end}}  
        # {{- if .Values.env.secrets}}  
        # - secretRef:  
        #     name: {{.Values.name}}  
        # {{- end}}  
        # {{- end}}