apiVersion: apps/v1  
kind: Deployment  
metadata:  
  name: cd-deployment  
spec:  
  replicas: 3  
  selector:  
    matchLabels:  
      app: cd  
  template:  
    metadata:  
      labels:  
        app: cd  
    spec:  
      imagePullSecrets:  
      - name: cd
      containers:  
      - name: cd  
        image: raphaelhoffa/ci