apiVersion: apps/v1
kind: Deployment
metadata:
  name: raphael-deployment
  namespace: raphael-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: raphael-app
  template:
    metadata:
      labels:
        app: raphael-app
    spec:
      containers:
      - name: raphaelhoffa/ci
        image: raphaelhoffa/ci:45
        imagePullPolicy: Always
        ports:
        - containerPort: 8080