apiVersion: apps/v1
kind: Deployment
metadata:
  name: raphael-deployment
  namespace: raphael-namespace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: raphael-app
  template:
    metadata:
      labels:
        app: raphael-app
    spec:
      containers:
      - name: raphael-container
        image: raphaelhoffa/ci
        ports:
        - containerPort: 80