apiVersion: v1  
kind: Service  
metadata:  
  name: cd-svc  
spec:  
  type: {{.Values.serviceType}}  
  ports:  
  - port: 80  
    targetPort: 8080 
    protocol: TCP  
  selector:  
    app: cd-svc