apiVersion: v1
kind: Service
metadata:
  name: raphael-ci-service
  namespace: raphael-deployment
  labels:
    app: raphael-ci
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: raphael-ci